version: "3"
services:
  workout-rival-service:
    image: workout-rival-service:latest
    links:
      - arangodb
    depends_on:
      - arangodb
    environment:
      ARANGO_ROOT_PASSWORD: "root"
    ports:
      - "8080:8080"

  arangodb:
    image: arangodb:latest
    container_name: "workout-rival-arangodb"
    restart: always
    environment:
      ARANGO_ROOT_PASSWORD: "root"
    ports:
      - "8529:8529"