spring:
  application:
    name: WorkoutRival

arangodb:
  host: localhost
  port: 8529

---
spring:
  profiles:
    active: docker
  boot:
    admin:
      client:
        url: [http://admin:1111]
        auto-registration: true
        username: admin
        password: admin
        instance:
          prefer-ip: true

management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

arangodb:
  host: arangodb
  port: 8529