spring:
  application:
    name: WorkoutRival

arangodb:
  host: localhost
  port: 8529
---
spring:
  profiles:
    active: dev

  thymeleaf:
    enabled: false
  boot:
    admin:
      client:
        url: [http://localhost:1111]
        auto-registration: true
        username: admin
        password: admin
        instance:
          prefer-ip: true

management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

arangodb:
  host: localhost
  port: 8529

---
spring:
  profiles:
    active: docker
  thymeleaf:
    enabled: false
  boot:
    admin:
      client:
        url: [http://admin:1111]
        auto-registration: true
        username: admin
        password: admin
        instance:
          prefer-ip: true

management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

arangodb:
  host: arangodb
  port: 8529

email:
  host: smtp.gmail.com
  port: 465
  username: workoutrivalservice@gmail.com
  password: ${SERVICE_EMAIL_PASSWORD}
---